Feature/members
paulvazbad/roborregosweb2 pull request #2
Opened 2018-10-16 20:37 UTC by gallosanchez23

2018-10-16 20:47 UTC, paulvazbad commented
Revisa los conflicts en la terminal plz

2018-10-16 20:48 UTC, paulvazbad requested changes

2018-10-16 20:48 UTC, paulvazbad commented on src/App.js
> +
```suggestion
<Header/>
```

2018-10-30 21:24 UTC, paulvazbad approved these changes

2018-10-30 21:34 UTC, diegocardozo167 approved these changes
Thank you for the fix!

2018-11-06 22:01 UTC, merged